export enum ErrorCode {
    ALREADY_LOGGED_OUT = 'ALREADY_LOGGED_OUT',
    REFRESH_TOKEN_IS_NOT_VALID = 'REFRESH_TOKEN_IS_NOT_VALID',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    USER_LOGGED_OUT = 'USER_LOGGED_OUT',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN',
    NO_AUTH_HEADER_PROVIDED = 'NO_AUTH_HEADER_PROVIDED',
    INVALID_AUTH_HEADER_PROVIDED = 'INVALID_AUTH_HEADER_PROVIDED',
    TOKEN_IS_NOT_ACTUAL = 'TOKEN_IS_NOT_ACTUAL',
    UNHANDLED_SERVER_ERROR = 'UNHANDLED_SERVER_ERROR',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
}

export default class ResponseError extends Error {

    code: ErrorCode;

    constructor(code: ErrorCode, message: string) {
        super(message);
        this.code = code;
    }
}

export const ErrorResponseStatusMaps = {
    [ErrorCode.ALREADY_LOGGED_OUT]: 409,
    [ErrorCode.ALREADY_LOGGED_IN]: 409,
    [ErrorCode.USER_LOGGED_OUT]: 409,
    [ErrorCode.TOKEN_EXPIRED]: 403,
    [ErrorCode.USER_LOGGED_OUT]: 409,
    [ErrorCode.INVALID_CREDENTIALS]: 400,
    [ErrorCode.EMAIL_ALREADY_REGISTERED]: 409,
    [ErrorCode.NO_AUTH_HEADER_PROVIDED]: 400,
    [ErrorCode.INVALID_AUTH_HEADER_PROVIDED]: 400,
    [ErrorCode.TOKEN_IS_NOT_ACTUAL]: 403,
    [ErrorCode.UNHANDLED_SERVER_ERROR]: 500,
    [ErrorCode.USER_NOT_FOUND]: 404,
    [ErrorCode.REFRESH_TOKEN_IS_NOT_VALID]: 403
}